# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('username', models.CharField(max_length=10, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.CharField(max_length=1000, verbose_name='内容')),
                ('cre_date', models.DateField(verbose_name='作成日時')),
                ('username', models.CharField(max_length=10, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('cd', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='コード')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.SET_DEFAULT, to='sampleapp.PostStatus', verbose_name='状況'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Post', verbose_name='投稿'),
        ),
    ]
